apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}-{{ .Values.slurmdbd.name }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.slurmdbd.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: slurmdbd
  {{- if .Values.slurmdbd.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.slurmdbd.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.slurmdbd.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- if .Values.slurmdbd.updateStrategy }}
  updateStrategy: {{- toYaml .Values.slurmdbd.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.slurmdbd.podLabels .Values.slurmdbd.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: slurmdbd
  serviceName: {{ .Values.slurmdbd.service.name }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: slurmdbd
      annotations:
        {{- if .Values.slurmdbd.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.slurmdbd.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "slurm.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "slurm.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.slurmdbd.automountServiceAccountToken }}
      shareProcessNamespace: true
      {{- if .Values.slurmdbd.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmdbd.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.slurmdbd.podAffinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.slurmdbd.podAntiAffinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.slurmdbd.nodeAffinityPreset.type "key" .Values.slurmdbd.nodeAffinityPreset.key "values" .Values.slurmdbd.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      hostNetwork: {{ .Values.slurmdbd.hostNetwork }}
      {{- if .Values.slurmdbd.dnsPolicy  }}
      dnsPolicy: {{ .Values.slurmdbd.dnsPolicy }}
      {{- end }}
      {{- if .Values.slurmdbd.dnsConfig }}
      dnsConfig: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.dnsConfig "context" $) | nindent 8 }}
      {{- else }}
      dnsConfig:
        searches:
          - {{ .Values.slurmctld.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
      {{- end }}
      hostIPC: {{ .Values.slurmdbd.hostIPC }}
      {{- if .Values.slurmdbd.priorityClassName }}
      priorityClassName: {{ .Values.slurmdbd.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.slurmdbd.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmdbd.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmdbd.schedulerName }}
      schedulerName: {{ .Values.slurmdbd.schedulerName | quote }}
      {{- end }}
      {{- if .Values.slurmdbd.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmdbd.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.slurmdbd.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmdbd.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.slurmdbd.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        - name: init-permission
          image: {{ .Values.image.mirror.registry }}docker.io/library/busybox:1.37.0-glibc
          command: ["sh", "-c", "chmod 755 /run/munge && chown 1108:1108 /run/munge"]
          volumeMounts:
            - name: munge-socket-file
              mountPath: /run/munge
      containers:
        - name: munged
          image: "{{ .Values.munged.image.registry }}/{{ .Values.munged.image.repository }}:{{ .Values.munged.image.tag }}"
          imagePullPolicy: {{ .Values.munged.image.pullPolicy }}
          {{- if .Values.munged.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.munged.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.munged.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.munged.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.munged.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.munged.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.munged.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.munged.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.munged.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.munged.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: munge-socket-file
              mountPath: /run/munge
            {{- if .Values.munged.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.munged.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        - name: slurmdbd
          image: "{{ .Values.slurmdbd.image.registry }}/{{ .Values.slurmdbd.image.repository }}:{{ .Values.slurmdbd.image.tag }}"
          imagePullPolicy: {{ .Values.slurmdbd.image.pullPolicy }}
          {{- if .Values.slurmdbd.containerSecurityContext }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.slurmdbd.containerSecurityContext "context" $) | nindent 12 }}
          {{- else }}
          securityContext:
            privileged: true
          {{- end }}
          {{- if .Values.slurmdbd.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.slurmdbd.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.slurmdbd.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.slurmdbd.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.slurmdbd.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.slurmdbd.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.slurmdbd.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.slurmdbd.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.slurmdbd.extraEnvVarsSecret "context" $) }}
            {{- end }}
          ports:
            - name: ssh
              containerPort: {{ .Values.slurmdbd.service.ssh.port }}
            - name: slurmdbd
              containerPort: {{ .Values.slurmdbd.service.slurmdbd.port }}
            {{- if .Values.slurmdbd.extraContainerPorts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.extraContainerPorts "context" $) | nindent 12 }}
            {{- end }}
          {{- if .Values.slurmdbd.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.slurmdbd.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.slurmdbd.livenessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: ssh
          {{- end }}
          {{- if .Values.slurmdbd.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.slurmdbd.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.slurmdbd.readinessProbe "enabled" "path") "context" $) | nindent 12 }}
            tcpSocket:
              port: ssh
          {{- end }}
          {{- if .Values.slurmdbd.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdbd.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.slurmdbd.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.slurmdbd.startupProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: ssh
          {{- end }}
          {{- if .Values.slurmdbd.resources }}
          resources: {{- toYaml .Values.slurmdbd.resources | nindent 12 }}
          {{- else if ne .Values.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: ssh-keys
              mountPath: /root/.ssh
              readOnly: true
            - name: slurmdbd-conf-file
              mountPath: /opt/slurm/slurmdbd.conf
              subPath: slurmdbd.conf
            - name: cgroup-conf-file
              mountPath: /etc/slurm/cgroup.conf
              subPath: cgroup.conf
            - name: munge-socket-file
              mountPath: /run/munge
            {{- if .Values.slurmdbd.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.slurmdbd.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
      volumes:
        - name: ssh-keys
          secret:
            secretName: {{ .Values.auth.ssh.secret.name }}
            items:
              - key: {{ .Values.auth.ssh.secret.keys.private }}
                path: {{ .Values.auth.ssh.secret.keys.private }}
                mode: 256
              - key: {{ .Values.auth.ssh.secret.keys.public }}
                path: {{ .Values.auth.ssh.secret.keys.public }}
                mode: 444
              - key: {{ .Values.auth.ssh.secret.keys.authorizedKeys }}
                path: {{ .Values.auth.ssh.secret.keys.authorizedKeys }}
                mode: 384
        - name: slurmdbd-conf-file
          configMap:
            name: {{ include "common.names.fullname" . }}-slurmdbd-conf
        - name: cgroup-conf-file
          configMap:
            name: {{ include "common.names.fullname" . }}-cgroup-conf
        - name: munge-socket-file
          emptyDir: {}
        {{- if .Values.slurmdbd.extraVolumes }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.slurmdbd.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
