apiVersion: {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}-slurmd-gpu
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.slurmdGPU.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: slurmd-gpu
  {{- if .Values.slurmdGPU.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.slurmdGPU.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.slurmdGPU.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- if .Values.slurmdGPU.updateStrategy }}
  updateStrategy: {{- toYaml .Values.slurmdGPU.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.slurmdGPU.podLabels .Values.slurmdGPU.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: slurmd-gpu
  serviceName: {{ .Values.slurmdGPU.service.name }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: slurmd-gpu
      annotations:
        {{- if .Values.slurmdGPU.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.slurmdGPU.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "slurm.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "slurm.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.slurmdGPU.automountServiceAccountToken }}
      shareProcessNamespace: true
      {{- if .Values.slurmdGPU.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmdGPU.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.slurmdGPU.podAffinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.slurmdGPU.podAntiAffinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.slurmdGPU.nodeAffinityPreset.type "key" .Values.slurmdGPU.nodeAffinityPreset.key "values" .Values.slurmdGPU.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      hostNetwork: {{ .Values.slurmdGPU.hostNetwork }}
      {{- if .Values.slurmdGPU.dnsPolicy  }}
      dnsPolicy: {{ .Values.slurmdGPU.dnsPolicy }}
      {{- end }}
      {{- if .Values.slurmdGPU.dnsConfig }}
      dnsConfig: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.dnsConfig "context" $) | nindent 8 }}
      {{- else }}
      dnsConfig:
        searches:
          - {{ .Values.slurmctld.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
          - {{ .Values.slurmdCPU.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
          - {{ .Values.slurmdGPU.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
      {{- end }}
      hostIPC: {{ .Values.slurmdGPU.hostIPC }}
      {{- if .Values.slurmdGPU.priorityClassName }}
      priorityClassName: {{ .Values.slurmdGPU.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.slurmdGPU.nodeName }}
      nodeName: {{ .Values.slurmdGPU.nodeName | quote }}
      {{- end }}
      {{- if .Values.slurmdGPU.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmdGPU.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmdGPU.schedulerName }}
      schedulerName: {{ .Values.slurmdGPU.schedulerName | quote }}
      {{- end }}
      {{- if .Values.slurmdGPU.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmdGPU.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.slurmdGPU.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmdGPU.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.slurmdGPU.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        - name: init-permission
          {{- if and .Values.image.mirror.registry (ne .Values.image.mirror.registry "") }}
          image: {{ .Values.image.mirror.registry }}/docker.io/library/busybox:1.37.0-glibc
          {{- else }}
          image: docker.io/library/busybox:1.37.0-glibc
          {{- end }}
          command: ["sh", "-c", "chmod 755 /run/munge && chown 1108:1108 /run/munge"]
          volumeMounts:
            - name: munge-socket-file
              mountPath: /run/munge
      containers:
        - name: munged
          image: "{{ .Values.munged.image.registry }}/{{ .Values.munged.image.repository }}:{{ .Values.munged.image.tag }}"
          imagePullPolicy: {{ .Values.munged.image.pullPolicy }}
          {{- if .Values.munged.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.munged.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.munged.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.munged.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.munged.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.munged.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.munged.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.munged.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.munged.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.munged.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: munge-socket-file
              mountPath: /run/munge
            {{- if .Values.munged.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.munged.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        - name: slurmd-gpu
          image: "{{ .Values.slurmdGPU.image.registry }}/{{ .Values.slurmdGPU.image.repository }}:{{ .Values.slurmdGPU.image.tag }}"
          imagePullPolicy: {{ .Values.slurmdGPU.image.pullPolicy }}
          {{- if .Values.slurmdGPU.containerSecurityContext }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.slurmdGPU.containerSecurityContext "context" $) | nindent 12 }}
          {{- else }}
          securityContext:
            privileged: true
          {{- end }}
          {{- if .Values.slurmdGPU.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.slurmdGPU.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.slurmdGPU.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.slurmdGPU.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.slurmdGPU.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.slurmdGPU.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.slurmdGPU.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.slurmdGPU.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.extraEnvVarsSecret "context" $) }}
            {{- end }}
          ports:
            - name: ssh
              containerPort: {{ .Values.slurmdGPU.service.ssh.port }}
            - name: slurmd
              containerPort: {{ .Values.slurmdGPU.service.slurmd.port }}
            {{- if .Values.slurmdGPU.extraContainerPorts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.extraContainerPorts "context" $) | nindent 12 }}
            {{- end }}
          {{- if .Values.slurmdGPU.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.slurmdGPU.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.slurmdGPU.livenessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: ssh
          {{- end }}
          {{- if .Values.slurmdGPU.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.slurmdGPU.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.slurmdGPU.readinessProbe "enabled" "path") "context" $) | nindent 12 }}
            tcpSocket:
              port: ssh
          {{- end }}
          {{- if .Values.slurmdGPU.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.slurmdGPU.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.slurmdGPU.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.slurmdGPU.startupProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: ssh
          {{- end }}
          {{- if .Values.slurmdGPU.resources }}
          resources: {{- toYaml .Values.slurmdGPU.resources | nindent 12 }}
          {{- else if ne .Values.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: ssh-keys
              mountPath: /root/.ssh
              readOnly: true
            - name: shared-storage
              mountPath: /data
            - name: slurm-conf-file
              mountPath: /etc/slurm/slurm.conf
              subPath: slurm.conf
            - name: cgroup-conf-file
              mountPath: /etc/slurm/cgroup.conf
              subPath: cgroup.conf
            - name: munge-socket-file
              mountPath: /run/munge
            {{- if .Values.slurmdGPU.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.slurmdGPU.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
      volumes:
        - name: ssh-keys
          secret:
            secretName: {{ .Values.auth.ssh.secret.name }}
            items:
              - key: {{ .Values.auth.ssh.secret.keys.private }}
                path: {{ .Values.auth.ssh.secret.keys.private }}
                mode: 256
              - key: {{ .Values.auth.ssh.secret.keys.public }}
                path: {{ .Values.auth.ssh.secret.keys.public }}
                mode: 444
              - key: {{ .Values.auth.ssh.secret.keys.authorizedKeys }}
                path: {{ .Values.auth.ssh.secret.keys.authorizedKeys }}
                mode: 384
        - name: shared-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.shared.name }}
        - name: slurm-conf-file
          configMap:
            name: {{ include "common.names.fullname" . }}-slurm-conf
        - name: cgroup-conf-file
          configMap:
            name: {{ include "common.names.fullname" . }}-cgroup-conf
        - name: munge-socket-file
          emptyDir: {}
        {{- if .Values.slurmdGPU.extraVolumes }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.slurmdGPU.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
