apiVersion:  {{ include "common.capabilities.statefulset.apiVersion" . }}
kind: StatefulSet
metadata:
  name: {{ include "common.names.fullname" . }}-{{ .Values.slurmctld.name }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.slurmctld.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: slurmctld
  {{- if .Values.slurmctld.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.slurmctld.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.slurmctld.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- if .Values.slurmctld.updateStrategy }}
  updateStrategy: {{- toYaml .Values.slurmctld.updateStrategy | nindent 4 }}
  {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.slurmctld.podLabels .Values.slurmctld.commonLabels ) "context" . ) }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
      app.kubernetes.io/component: slurmctld
  serviceName: {{ .Values.slurmctld.service.name }}
  template:
    metadata:
      labels: {{- include "common.labels.standard" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: slurmctld
      annotations:
        {{- if .Values.slurmctld.podAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.slurmctld.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
    spec:
      {{- include "slurm.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "slurm.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.slurmctld.automountServiceAccountToken }}
      shareProcessNamespace: true
      {{- if .Values.slurmctld.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmctld.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.slurmctld.podAffinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.slurmctld.podAntiAffinityPreset "customLabels" $podLabels "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.slurmctld.nodeAffinityPreset.type "key" .Values.slurmctld.nodeAffinityPreset.key "values" .Values.slurmctld.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      hostNetwork: {{ .Values.slurmctld.hostNetwork }}
      {{- if .Values.slurmctld.dnsPolicy  }}
      dnsPolicy: {{ .Values.slurmctld.dnsPolicy }}
      {{- end }}
      {{- if .Values.slurmctld.dnsConfig }}
      dnsConfig: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.dnsConfig "context" $) | nindent 8 }}
      {{- else }}
      dnsConfig:
        searches:
          - {{ .Values.slurmd.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
          - {{ .Values.slurmdbd.service.name }}.{{ .Release.Namespace }}.svc.cluster.local
      {{- end }}
      hostIPC: {{ .Values.slurmctld.hostIPC }}
      {{- if .Values.slurmctld.priorityClassName }}
      priorityClassName: {{ .Values.slurmctld.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.slurmctld.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmctld.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmctld.schedulerName }}
      schedulerName: {{ .Values.slurmctld.schedulerName | quote }}
      {{- end }}
      {{- if .Values.slurmctld.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmctld.podSecurityContext.enabled }}
      securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.slurmctld.podSecurityContext "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slurmctld.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.slurmctld.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        - name: check-dns
          image: {{ .Values.image.mirror.registry }}docker.io/library/busybox:1.37.0-glibc
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo "waiting for slurmdbd dns to be ready..."
              until nc -z -w 3 $SLURMDBD_HOSTNAME $SLURMDBD_PORT; do
                echo "connection is not ready yet, retrying..."
                sleep 3
              done
          env:
            - name: SLURMDBD_HOSTNAME
              value: {{ include "common.names.fullname" . }}-{{ .Values.slurmdbd.name }}-0
            - name: SLURMDBD_PORT
              value: {{ .Values.slurmdbd.service.slurmdbd.port | quote }}
        - name: init-permission
          image: {{ .Values.image.mirror.registry }}docker.io/library/busybox:1.37.0-glibc
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "chmod 755 /run/munge && chown 1108:1108 /run/munge"]
          volumeMounts:
            - name: munge-socket-file
              mountPath: /run/munge
      containers:
        - name: munged
          image: "{{ .Values.munged.image.registry }}/{{ .Values.munged.image.repository }}:{{ .Values.munged.image.tag }}"
          imagePullPolicy: {{ .Values.munged.image.pullPolicy }}
          {{- if .Values.munged.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.munged.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.munged.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.munged.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.munged.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.munged.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.munged.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.munged.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.munged.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.munged.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: munge-socket-file
              mountPath: /run/munge
            {{- if .Values.munged.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.munged.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
        - name: slurmctld
          image: "{{ .Values.slurmctld.image.registry }}/{{ .Values.slurmctld.image.repository }}:{{ .Values.slurmctld.image.tag }}"
          imagePullPolicy: {{ .Values.slurmctld.image.pullPolicy }}
          {{- if .Values.slurmctld.containerSecurityContext }}
          securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.slurmctld.containerSecurityContext "context" $) | nindent 12 }}
          {{- else }}
          securityContext:
            privileged: true
          {{- end }}
          {{- if .Values.slurmctld.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.slurmctld.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.slurmctld.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.slurmctld.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.args "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.slurmctld.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          env:
            {{- if .Values.slurmctld.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            {{- if .Values.slurmctld.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.slurmctld.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.slurmctld.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.slurmctld.extraEnvVarsSecret "context" $) }}
            {{- end }}
          ports:
            - name: ssh
              containerPort: {{ .Values.slurmctld.service.ssh.port }}
            - name: slurmctld
              containerPort: {{ .Values.slurmctld.service.slurmctld.port }}
            {{- if .Values.slurmctld.extraContainerPorts }}
            {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.extraContainerPorts "context" $) | nindent 12 }}
            {{- end }}
          {{- if .Values.slurmctld.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.slurmctld.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.slurmctld.livenessProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: ssh
          {{- end }}
          {{- if .Values.slurmctld.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.slurmctld.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.slurmctld.readinessProbe "enabled" "path") "context" $) | nindent 12 }}
            tcpSocket:
              port: ssh
          {{- end }}
          {{- if .Values.slurmctld.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.slurmctld.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.slurmctld.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.slurmctld.startupProbe "enabled") "context" $) | nindent 12 }}
            tcpSocket:
              port: ssh
          {{- end }}
          {{- if .Values.slurmctld.resources }}
          resources: {{- toYaml .Values.slurmctld.resources | nindent 12 }}
          {{- else if ne .Values.resourcesPreset "none" }}
          resources: {{- include "common.resources.preset" (dict "type" .Values.resourcesPreset) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: ssh-keys
              mountPath: /root/.ssh
              readOnly: true
            - name: shared-storage
              mountPath: /data
            - name: slurm-conf-file
              mountPath: /etc/slurm/slurm.conf
              subPath: slurm.conf
            - name: cgroup-conf-file
              mountPath: /etc/slurm/cgroup.conf
              subPath: cgroup.conf
            - name: munge-socket-file
              mountPath: /run/munge
            {{- if .Values.slurmctld.extraVolumeMounts }}
            {{- include "common.tplvalues.render" ( dict "value" .Values.slurmctld.extraVolumeMounts "context" $) | nindent 12 }}
            {{- end }}
      volumes:
        - name: ssh-keys
          secret:
            secretName: {{ .Values.auth.ssh.secret.name }}
            items:
              - key: {{ .Values.auth.ssh.secret.keys.private }}
                path: {{ .Values.auth.ssh.secret.keys.private }}
                mode: 256
              - key: {{ .Values.auth.ssh.secret.keys.public }}
                path: {{ .Values.auth.ssh.secret.keys.public }}
                mode: 444
              - key: {{ .Values.auth.ssh.secret.keys.authorizedKeys }}
                path: {{ .Values.auth.ssh.secret.keys.authorizedKeys }}
                mode: 384
        - name: shared-storage
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.shared.name }}
        - name: slurm-conf-file
          configMap:
            name: {{ include "common.names.fullname" . }}-slurm-conf
        - name: cgroup-conf-file
          configMap:
            name: {{ include "common.names.fullname" . }}-cgroup-conf
        - name: munge-socket-file
          emptyDir: {}
        {{- if .Values.slurmctld.extraVolumes }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.slurmctld.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
